### ISSUE TITLE
Update Snakemake dependencies in Oncopipe

### ISSUE THREAD

**Issue by lkhilton** [LCR-BCCRC/lcr-modules#153] opened 2020-12-21 17:49 UTC
Snakemake has fixed the issues we had been agonizing over in #87, and I'm now confident that oncopipe is compatible with Snakemake > 5.27. @BrunoGrandePhD, can you please offer some guidance on how to update this so that `pip install -e oncopipe` allows more recent versions of Snakemake?

**Comment by BrunoGrandePhD** [comment] 2021-01-05 03:43
Back from vacation. 

[This](https://github.com/LCR-BCCRC/lcr-modules/blob/master/oncopipe/setup.py#L25) is the line you need to tweak. Specifically, you probably still want to omit the problematic versions of Snakemake, so you can update the entry to something like `"snakemake>=5.4,<5.19,>=5.27"`. 

On a separate note, if you want to make sure that pip installs the latest available version of Snakemake when it install oncopipe, you can use this command: `pip install --upgrade --upgrade-strategy eager -e oncopipe`.

**Comment by lkhilton** [comment] 2021-01-05 16:17
Thank you!

**Comment by rdmorin** [comment] 2021-01-05 17:02
Could we take this opportunity to add the packaging module as a dependency also? It is needed for the version checking we are about to implement.

**Comment by lkhilton** [comment] 2021-01-05 17:05
Would we need to add it to the old versions retroactively?

**Comment by rdmorin** [comment] 2021-01-05 17:27
I think we resolve this by checking for the dependency and asking the user to upgrade if it's missing. This is effectively going to catch most cases of people using pre-1.0.11 installations of oncopipe but we'll check the version as well.

**Comment by BrunoGrandePhD** [comment] 2021-01-06 15:22
If I recall correctly, PyPI prevents you from updating past versions for the sake of reproducibility. 

To deploy to PyPI, you need to update the oncopipe version in `__version__.py`, which is already done, and then push a new tag (in this case, `v1.0.11`, which is missing) to GitHub. That will trigger the package to be deployed to PyPI automatically using [GitHub Actions](https://github.com/LCR-BCCRC/lcr-modules/actions?query=workflow%3A%22Upload+Python+Package%22) (_i.e._ via continuous integration). This automation is described in this [YAML file](https://github.com/LCR-BCCRC/lcr-modules/blob/master/.github/workflows/python-publish.yml). The username and password are stored as secrets (key-value pairs that you cannot read after setting them) on the repository. 

The commands for tagging would look like this:

```
git checkout master. # If not already on the `master` branch
git tag v1.0.11
git push --tags
```

**Comment by rdmorin** [comment] 2021-01-06 16:18
Thanks Bruno. I've just done this. Is this something only admins can do or can anyone push a new tag to Master?

**Comment by BrunoGrandePhD** [comment] 2021-01-06 18:34
Tags are simply references to specific commits, so anyone with write-access to the repo should be able to publish new tags. When you do, you can monitor the continuous integration (CI) [here](https://github.com/LCR-BCCRC/lcr-modules/actions) to make sure it runs successfully.

**Comment by Lakshay-sethi** [comment] 2021-01-06 21:43
@BrunoGrandePhD Do you know what's the process to update the package on conda?

**Comment by lkhilton** [comment] 2021-01-06 22:09
It's never been on Conda, but you can use Conda to install and track packages installed through pip. Documentation is [here](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment).

**Comment by Lakshay-sethi** [comment] 2021-01-06 22:15
I was talking about updating oncopipe version to  1.0.11 in conda package manager.

**Comment by lkhilton** [comment] 2021-01-06 22:18
I take it back, I didn't think it had been added to Conda. Never mind.

**Comment by rdmorin** [comment] 2021-01-06 22:33
I was surprised too! I don't know how that happened but it's a recent version too.

**Comment by rdmorin** [comment] 2021-01-06 22:36
Since we are recommending people install from pip it is somewhat irrelevant but I am interested in knowing how version 1.0.10 got there.

**Comment by BrunoGrandePhD** [comment] 2021-01-07 00:01
I never put `oncopipe` on conda (more specifically, in the bioconda channel). My best guess is that Bioconda re-publishes Python packages on PyPI tagged with the `Bio-Informatics` topic (see [this line](https://github.com/LCR-BCCRC/lcr-modules/blob/master/oncopipe/setup.py#L33)). 

Edit: So, the process of updating `oncopipe` on conda might be to just post an update on PyPI, and Bioconda's infrastructure will take care of the rest. It would be useful to know what the latency is.

**Comment by Lakshay-sethi** [comment] 2021-01-11 18:11
The conda update happened approximately 5 hours ago, so the latency is 5 days.

**Comment by Kdreval** [comment] 2021-10-01 23:31
This has been addressed in PR https://github.com/LCR-BCCRC/lcr-modules/pull/165 Now oncopipe will work with versions >=5.31 of Snakemake. Closing this issue for now

**Closed as completed by Kdreval** 2021-10-01 23:31 UTC
