### ISSUE TITLE
Sequenza still has an installation error

### ISSUE THREAD

**Issue by rdmorin** [LCR-BCCRC/lcr-modules#93] opened 2020-09-01 19:36 UTC
I just got this error using the version of sequenza run in the demo (Master branch). This needs to be fixed ASAP. 

```
Downloading GitHub repo ShixiangWang/copynumber@master
Running `R CMD build`...
* installing *source* package ‘copynumber’ ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
ERROR: lazy loading failed for package ‘copynumber’
* removing ‘/home/rmorin/miniconda3/envs/6fb9fb2d/lib/R/library/copynumber’
* restoring previous ‘/home/rmorin/miniconda3/envs/6fb9fb2d/lib/R/library/copynumber’
Error: Failed to install 'copynumber' from GitHub:
  (converted from warning) installation of package ‘/tmp/Rtmp2LObYX/file71466c6c49c2/copynumber_1.29.0.9000.tar.gz’ had non-zero exit status
```

**Comment by Kdreval** [comment] 2020-09-01 20:08
Looks like the same error as in #72 I am trying to find a solution by testing addition of environmental variable `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="TRUE")` before installing the package, but could not reproduce this error on GSC, Thanos, or my local computer

**Comment by lkhilton** [comment] 2020-09-01 20:18
Ryan, can you shed any light on why it looks like this package is trying to install in a conda env in your home directory instead of `/projects/rmorin_scratch/conda_environments`?

**Comment by Kdreval** [comment] 2020-09-01 20:26
Also, in the current version of demo project on Master, the sequenza version in demo Snakefile is 1.2. I introduced my "fix" to it in the version 1.4. Is it possible to try the newer version of sequenza to see if that will work?

**Comment by rdmorin** [comment] 2020-09-01 20:32
I'm testing this on Cedar and haven't set a conda_prefix.

**Comment by rdmorin** [comment] 2020-09-01 20:32
This was using sequenza 1.4.

```
configfile: "../modules/sequenza/1.4/config/default.yaml"

...

include: "../modules/sequenza/1.4/sequenza.smk"

...

rules._sequenza_all.input,
```

**Comment by rdmorin** [comment] 2020-09-01 20:37
It's very hard to troubleshoot this because if I load that environment and run "R" I just get a Segmentation fault.

**Comment by rdmorin** [comment] 2020-09-01 20:44
```
conda env create -f ../modules/sequenza/1.4/envs/r-sequenza-3.0.0.yaml
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.8.3
  latest version: 4.8.4

Please update conda by running

    $ conda update -n base -c defaults conda


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test-r-sequenza
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(6fb9fb2d) [rmorin@cedar5 demo]$ conda activate test-r-sequenza
(test-r-sequenza) [rmorin@cedar5 demo]$ R
Segmentation fault
```

**Comment by Kdreval** [comment] 2020-09-01 20:47
While testing on Thanos, I got a different type of error. Is it possible same thing related to tar archive is happening on Cider, but gives different error? Maybe it is R-version related, or `remotes` version? 
```
Downloading GitHub repo ShixiangWang/copynumber@master
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
tar: This does not look like a tar archive

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

 Error in getrootdir(untar(src, list = TRUE)) : 
  length(file_list) > 0 is not TRUE
 
In addition: Warning messages:
1: In utils::untar(tarfile, ...) :
  ‘tar -xf '/tmp/RtmpWBkiTi/filedf3552d8a2646.tar.gz' -C '/tmp/RtmpWBkiTi/remotesdf35567315d9'’ returned error code 2
2: In system(cmd, intern = TRUE) :
  running command 'tar -tf '/tmp/RtmpWBkiTi/filedf3552d8a2646.tar.gz'' had status 2
```

**Comment by rdmorin** [comment] 2020-09-01 20:48
@Kdreval I should have clarified that I'm running the demo on the branch you were working on, so I am in sync with your patch

**Comment by rdmorin** [comment] 2020-09-01 21:37
I managed to get this environment to build and get past this error when I ran this on cedar "manually" (conda env create -f ...)

**Comment by rdmorin** [comment] 2020-09-03 19:11
I still haven't gotten past this. The most recent error is:

```
Downloading GitHub repo ShixiangWang/copynumber@master
Running `R CMD build`...
ERROR: failed to lock directory ‘/home/rmorin/miniconda3/envs/6fb9fb2d/lib/R/library’ for modifying
Try removing ‘/home/rmorin/miniconda3/envs/6fb9fb2d/lib/R/library/00LOCK-copynumber’
Error: Failed to install 'copynumber' from GitHub:
  (converted from warning) installation of package ‘/tmp/RtmpMrXbUZ/file6d7a3b7dad1b/copynumber_1.29.0.9000.tar.gz’ had non-zero exit status
Execution halted
```

**Comment by Kdreval** [comment] 2020-09-03 19:33
That is probably unrelated, but I mentioned that it is always installing from `@master` when it fails on this server. In contrast, when I was trying on my local computer and on GSC Rstudio, it is installing from `@HEAD`. I wonder if there is some difference there. Although I am not sure if that is an option to specify.

**Comment by rdmorin** [comment] 2020-09-03 19:51
I am strongly leaning towards just going back to a single "install" rule that runs the installation and ensures success before launching the jobs. The implementation of auto-installation while the script is first run seems to have a series of rippling negative effects.

**Comment by Kdreval** [comment] 2020-09-03 19:54
Sure, let's do that. I am glad there is an opportunity to test all this changes in the new setting, which helps to determine how useful these changes are.

**Comment by BrunoGrandePhD** [comment] 2020-09-03 21:08
I wish I had been able to create the copynumber-hg38 conda package. Sadly, I couldn't get pass some errors during the build process. I agree that pre-installing might pre-empt issues here. Alternatively, a Singularity image would also work, but I don't know if Cedar supports Singularity. 
https://github.com/BrunoGrandePhD/conda-packages

**Comment by rdmorin** [comment] 2020-09-03 21:29
Would it be any better to include copynumber-hg38 directly in our repo? I suppose if we are still using the same installation approach that won't make any difference. Are there alternative installation approaches (i.e. via a local file) if we can ensure the package is bundled with the repo?

**Comment by BrunoGrandePhD** [comment] 2020-09-03 21:52
I don't think it's necessary to include the package in our repo. The command for installing a local package isn't simpler. 

I just realized that you could install the package within the same rule before running the script. For example, you could use the following as the command in the [`shell` directive](https://github.com/LCR-BCCRC/lcr-modules/blob/master/modules/sequenza/1.4/sequenza.smk#L183-L184). This way, you aren't installing packages in the same process you want to use them. 
```
R -e 'BiocManager::install("copynumber")' 
    &&
R -e 'remotes::install_github("ShixiangWang/copynumber", dependencies = FALSE)' 
    &&
Rscript {input.run_sequenza} {input.seqz} {input.assembly} {input.chroms} {input.x_chrom} 
$(dirname {output.segments}) {threads} > {log.stdout} 2> {log.stderr}
```

**Comment by BrunoGrandePhD** [comment] 2020-09-03 21:56
Feel free to update the `remotes::install_github()` function call to point to a specific commit/version. For example, using the latest commit ID:.
```
R -e 'remotes::install_github("ShixiangWang/copynumber", ref = "b3de1b0", dependencies = FALSE)' 
```
This way, the version used in our module is stable. This could also be a module parameter.

**Comment by Kdreval** [comment] 2020-09-03 22:01
Is this approach going to install the package whenever the every sample is submitted to run? I am asking because when I was running the GAMBL samples, we realized that `remotes` is trying to check for the package update and install package every time we submit a sample to run, even if the package is already installed. Using it within snakemake to run hundreds of samples eventually caused `remotes` to fail package installation step.

**Comment by rdmorin** [comment] 2020-09-03 22:04
This would be coupled with a rule that is run only once per project (rather than per sample).

**Comment by rdmorin** [comment] 2020-09-03 22:16
@BrunoGrandePhD the solution you are suggesting still may lead to the same issue of many instances of the job trying to execute that installation command at essentially the same time, which is problematic.

**Comment by BrunoGrandePhD** [comment] 2020-09-03 22:23
Sorry, I forgot this rule was run once per sample.

**Comment by rdmorin** [comment] 2020-09-04 22:25
I think we have bigger problems. It looks like the failure on Cedar is due to a missing dependency. I've tried installing the bioconductor-genomeinfodbdata package and conda says it is already installed.

**Comment by rdmorin** [comment] 2020-09-04 23:43
I realized that changing the install_github line from 

dependencies = FALSE 

to

dependencies = TRUE

fixes this issue. Does anyone see a reason not to implement this fix?

**Comment by Kdreval** [comment] 2020-09-04 23:56
We are expecting the installation to happen once, and only once - so to my mind this fix can be used.

**Comment by BrunoGrandePhD** [comment] 2020-09-05 16:13
All dependencies of `copynumber` should be installed with the `BiocManager::install("copynumber")` line. My guess is that `bioconductor-genomeinfodbdata` was added as a dependency (perhaps in the forked version specifically) at a later point. This highlights the need to perhaps specify the commit ID in the `install_github()` call.

**Comment by rdmorin** [comment] 2020-09-05 16:20
If the patch I just submitted fixes things I'm hesitant to change anything again but I agree the commit should be added when this tool is next updated.

**Comment by BrunoGrandePhD** [comment] 2020-09-05 16:24
I wonder if a label system should be added to track these non-urgent feature requests for specific modules. This way, whenever someone updates a module, they can look for any issues tagged with `module/sequenza`, for example. Good or bad idea?

**Comment by rdmorin** [comment] 2020-09-05 18:11
I completely agree. I was thinking along these lines also but don't know what the right way to implement this is. I know we can add the "enhancement" tag but is there a way to link issues to specific modules?

**Comment by BrunoGrandePhD** [comment] 2020-09-05 18:23
For now, I would start with the exiting label system in GitHub (like I just did). Labels are easy to create on the fly, and they're easy to search for in the GitHub Issues interface.

**Comment by Kdreval** [comment] 2021-01-12 02:39
> I realized that changing the install_github line from
> 
> dependencies = FALSE
> 
> to
> 
> dependencies = TRUE
> 
> fixes this issue. Does anyone see a reason not to implement this fix?

I just tried running the module in Cedar with demo sample and it built all the environments and run from the first try. I think this solved installation problems and issue can be closed.

**Comment by oncogenomics** [comment] 2021-03-18 18:59
Closing this issue as the bug seems to be fixed with by changing the ```install_github``` line from

```dependencies = FALSE```

to

```dependencies = TRUE```

**Closed as completed by oncogenomics** 2021-03-18 18:59 UTC
Labels: module/sequenza
